# Generated by Django 3.2.13 on 2022-06-11 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mixxo_model',
            fields=[
                ('mixxo_key', models.IntegerField(primary_key=True, serialize=False)),
                ('mixxo_image', models.TextField()),
                ('mixxo_link', models.TextField()),
            ],
            options={
                'db_table': 'mixxo',
            },
        ),
        migrations.CreateModel(
            name='mixxo_rank',
            fields=[
                ('mixxo_rank_key', models.IntegerField(primary_key=True, serialize=False)),
                ('mixxo_rank_name', models.CharField(max_length=100)),
                ('mixxo_rank_link', models.TextField()),
            ],
            options={
                'db_table': 'mixxo_rank',
            },
        ),
        migrations.CreateModel(
            name='musinsa_model',
            fields=[
                ('musinsa_key', models.IntegerField(primary_key=True, serialize=False)),
                ('musinsa_image', models.TextField()),
                ('musinsa_link', models.TextField()),
            ],
            options={
                'db_table': 'musinsa',
            },
        ),
        migrations.CreateModel(
            name='musinsa_rank',
            fields=[
                ('musinsa_rank_key', models.IntegerField(primary_key=True, serialize=False)),
                ('musinsa_rank_name', models.CharField(max_length=100)),
                ('musinsa_rank_link', models.TextField()),
            ],
            options={
                'db_table': 'musinsa_rank',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='spao_model',
            fields=[
                ('spao_key', models.IntegerField(primary_key=True, serialize=False)),
                ('spao_image', models.TextField()),
                ('spao_link', models.TextField()),
            ],
            options={
                'db_table': 'spao',
            },
        ),
        migrations.CreateModel(
            name='spao_rank',
            fields=[
                ('spao_rank_key', models.IntegerField(primary_key=True, serialize=False)),
                ('spao_rank_name', models.CharField(max_length=100)),
                ('spao_rank_link', models.TextField()),
            ],
            options={
                'db_table': 'spao_rank',
            },
        ),
        migrations.CreateModel(
            name='FreePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='post_photo')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osoriapp.freepost')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osoriapp.post')),
            ],
        ),
    ]
