# Generated by Django 3.2.13 on 2022-06-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoriapp', '0005_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='freepost',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='post_photo'),
        ),
    ]
